[tool.commitizen]
name = "cz_conventional_commits"
version = "0.2.0"
tag_format = "v$version"
version_files = [
    "package.json",
]
bump_message = "bump: version $current_version → $new_version"
update_changelog_on_bump = true
